apiVersion: v1
kind: Service
metadata:
 name: helloworld-service
spec:
 type: ClusterIP
 selector:
   app: helloworld
   env: prod
 ports:
 - port: 8080
   targetPort: 8080
---
apiVersion: apps/v1 
kind: Deployment 
metadata: 
 name: helloworld-deployment 
spec: 
 replicas: 2 
 strategy: 
  type: Recreate 
 selector: 
  matchLabels: 
   app: helloworld 
 template: 
   metadata: 
    labels: 
     app: helloworld 
     env: prod 
   spec: 
    containers: 
    - name: hello-world
      image: hello-world
      imagePullPolicy: Never
        